disabled_rules:
  - line_length
  - type_name
  - switch_case_alignment
opt_in_rules:
  - empty_count
  - explicit_init
  - unused_parameter
included:
  - "ShareBox/Sources/**"
  - "ShareBox.Finder/**"
excluded:
  - Carthage
  - Pods
